version: '3'
volumes:
services:
 sut:
     build: .
     command: npm test
     depends_on:
         - DB
     networks:
         - web_sql_bridge
 redis:
    image: 'bitnami/redis:latest'
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    ports:
        - '6379:6379'
    depends_on:
        - DB
 DB:
     image: mysql:5.7
     container_name: mysql
     restart: always
     environment:
         - MYSQL_ROOT_PASSWORD=goon
         - MYSQL_DATABASE=TERRA_TEST
         - MYSQL_USER=tester
         - MYSQL_PASSWORD=goon
         - DATABASE_HOST=docker-mysql
     ports:
         - "3306:3306"
     healthcheck:
            test:  ["CMD", "mysqlshow --user=tester --password=goon TERRA_TEST| grep -v Wildcard | grep -o TERRA_TEST"]
            timeout: 1s
            retries: 120
     networks:
         - web_sql_bridge
volumes:
    appconf:

networks:
  web_sql_bridge:
    driver: bridge
