version: '2'
volumes:
services:
 web:
    build: .
    command: "npm start"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - DB
    networks:
        - web_sql_bridge

 redis:
    image: 'bitnami/redis:latest'
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    ports:
        - '6379:6379'
 DB:
     image: mysql:5.7
     container_name: mysql
     restart: always
     environment:
         - MYSQL_ROOT_PASSWORD=goon
         - MYSQL_DATABASE=TERRA_TEST
         - MYSQL_USER=tester
         - MYSQL_PASSWORD=goon
         - DATABASE_HOST=docker-mysql
     ports:
         - "3306:3306"
     networks:
         - web_sql_bridge
volumes:
    appconf:

networks:
  web_sql_bridge:
    driver: bridge
