version: 2
jobs:
  build:
    docker:
        steps:
          - checkout
          - run:
              name: Update npm
              command: sudo npm update
          - restore_cache:
              key: dependency-cache-{{ checksum "package.json" }}
          - run:
              name: Install Packages
              command: sudo npm install
          - save_cache:
              key: dependency-cache-{{ checksum "package.json" }}
              paths:
                - node_modules
  test:
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
