version: 1
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run: touch configKeys.json | echo $googleGeocode > configKeys.json | touch passwords.json | echo {"database":$databasePassword} > passwords.json
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar

  test:
    requires:
        - build
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
        - tests:
            name: Start Docker Container for Testing
            command: |
                docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from sut
  deploy:
    requires:
        - test
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
        - deploy:
            name: Push application Docker image
            command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                login="$(aws ecr get-login)"
                ${login}
                docker tag app ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/terra-repo
                docker push ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/terra-repo
              fi
workflows:
  version: 1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
              - build
      - deploy:
          requires:
              - test
